In [76]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [77]:
df=pd.read_csv("/Users/sam/Desktop/ML PRS/PR2/emails.csv")

In [78]:
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey   
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0  \
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry   
0       0       0    0               0         0         0   0    0  \
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [79]:
df.shape

(5172, 3002)

In [80]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [81]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay   
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0  \
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [82]:
df.tail()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0  \
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry   
5167    0       0    0               0         0         0   0    0  \
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5 rows x 3002 columns]

In [83]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [84]:
df.drop(columns="Email No.",inplace=True)

In [85]:
df

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay   
0       0   0    1    0    0   0    2    0    0   0  ...         0    0  \
1       8  13   24    6    6   2  102    1   27  18  ...         0    0   
2       0   0    1    0    0   0    8    0    0   4  ...         0    0   
3       0   5   22    0    5   1   51    2   10   1  ...         0    0   
4       7   6   17    1    5   2   57    0    9   3  ...         0    0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
5167    2   2    2    3    0   0   32    0    0   5  ...         0    0   
5168   35  27   11    2    6   5  151    4    3  23  ...         0    0   
5169    0   0    1    1    0   0   11    0    0   1  ...         0    0   
5170    2   7    1    0    2   1   28    2    0   8  ...         0    0   
5171   22  24    5    1    6   5  148    8    2  23  ...         0    0   

      valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0          0    0               0         0         0   0    0           0  
1          0    0               0         0         0   1    0           0  
2          0    0               0         0         0   0    0           0  
3          0    0               0         0         0   0    0           0  
4          0    0               0         0         0   1    0           0  
...      ...  ...             ...       ...       ...  ..  ...         ...  
5167       0    0               0         0         0   0    0           0  
5168       0    0               0         0         0   1    0           0  
5169       0    0               0         0         0   0    0           1  
5170       0    0               0         0         0   1    0           1  
5171       0    0               0         0         0   0    0           0  

[5172 rows x 3001 columns]

In [86]:
df.columns

Index(['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3001)

In [87]:
df['Prediction'].unique()

array([0, 1])

In [88]:
df['Prediction']=df['Prediction'].replace({0:'Not Spam',1:'Spam'})

In [89]:
df

the  to  ect  and  for  of    a  you  hou  in  ...  connevey  jay   
0       0   0    1    0    0   0    2    0    0   0  ...         0    0  \
1       8  13   24    6    6   2  102    1   27  18  ...         0    0   
2       0   0    1    0    0   0    8    0    0   4  ...         0    0   
3       0   5   22    0    5   1   51    2   10   1  ...         0    0   
4       7   6   17    1    5   2   57    0    9   3  ...         0    0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...       ...  ...   
5167    2   2    2    3    0   0   32    0    0   5  ...         0    0   
5168   35  27   11    2    6   5  151    4    3  23  ...         0    0   
5169    0   0    1    1    0   0   11    0    0   1  ...         0    0   
5170    2   7    1    0    2   1   28    2    0   8  ...         0    0   
5171   22  24    5    1    6   5  148    8    2  23  ...         0    0   

      valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0          0    0               0         0         0   0    0    Not Spam  
1          0    0               0         0         0   1    0    Not Spam  
2          0    0               0         0         0   0    0    Not Spam  
3          0    0               0         0         0   0    0    Not Spam  
4          0    0               0         0         0   1    0    Not Spam  
...      ...  ...             ...       ...       ...  ..  ...         ...  
5167       0    0               0         0         0   0    0    Not Spam  
5168       0    0               0         0         0   1    0    Not Spam  
5169       0    0               0         0         0   0    0        Spam  
5170       0    0               0         0         0   1    0        Spam  
5171       0    0               0         0         0   0    0    Not Spam  

[5172 rows x 3001 columns]

In [90]:
x=df.drop(columns='Prediction',axis=1)
y=df['Prediction']

In [91]:
x.columns

Index(['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in',
       ...
       'enhancements', 'connevey', 'jay', 'valued', 'lay', 'infrastructure',
       'military', 'allowing', 'ff', 'dry'],
      dtype='object', length=3000)

In [92]:
y.head()

0    Not Spam
1    Not Spam
2    Not Spam
3    Not Spam
4    Not Spam
Name: Prediction, dtype: object

In [93]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=1)

In [94]:
from sklearn.neighbors import KNeighborsClassifier

In [95]:
knn=KNeighborsClassifier()

In [96]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [97]:
y_pred=knn.predict(x_test)

In [98]:
print(y_pred)

['Not Spam' 'Spam' 'Not Spam' ... 'Spam' 'Not Spam' 'Not Spam']


In [99]:
asc=metrics.accuracy_score(y_test,y_pred)

In [100]:
print(asc)

0.8699472759226714


In [102]:
conf=metrics.confusion_matrix(y_test,y_pred)

In [103]:
print(conf)

[[1063  140]
 [  82  422]]


In [104]:
from sklearn.svm import SVC

In [106]:
svm=SVC()

In [107]:
svm.fit(x_train,y_train)

SVC()

In [109]:
y_pred=svm.predict(x_test)

In [110]:
print(y_pred)

['Not Spam' 'Spam' 'Not Spam' ... 'Not Spam' 'Not Spam' 'Not Spam']


In [111]:
print(metrics.accuracy_score(y_test,y_pred))

0.7914469830111306


In [112]:
print(metrics.confusion_matrix(y_test,y_pred))

[[1175   28]
 [ 328  176]]
